name: ci

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "preview/**"
    paths-ignore:
      - .github/dependabot.yml
      - LICENSE
      - README.md
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.release.outputs.version }}
      fullSemVer: ${{ steps.release.outputs.fullSemVer }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./
        id: release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "version=${{ needs.release.outputs.version }}"
          echo "fullSemVer=${{ needs.release.outputs.fullSemVer }}"
          echo "major=${{ needs.release.outputs.major }}"
          echo "minor=${{ needs.release.outputs.minor }}"
          echo "patch=${{ needs.release.outputs.patch }}"
