name: ci

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "preview/**"
    paths-ignore:
      - .github/dependabot.yml
      - LICENSE
      - README.md
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  release:
    #uses: f2calv/gha-workflows/.github/workflows/gha-release-versioning.yml@v1
    uses: f2calv/gha-workflows/.github/workflows/gha-release-versioning.yml@f2calv/2024-05-image-tagging
    permissions:
      contents: write
  
  debug:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "semVer=${{ needs.release.outputs.semVer }}"
          echo "fullSemVer=${{ needs.release.outputs.fullSemVer }}"
          echo "major=${{ needs.release.outputs.major }}"
          echo "minor=${{ needs.release.outputs.minor }}"
          echo "patch=${{ needs.release.outputs.patch }}"
